version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: newsapp-db
    hostname: db
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - dev-db:/var/lib/mysql
    networks:
      backend-network:
        ipv4_address: 10.5.0.50

  web:
    build: ./
    container_name: newsapp-web
    hostname: newsapp-web
    restart: always
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/app/src/
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      backend-network:
        ipv4_address: 10.5.0.10
  
  redis:
    image: redis:7.0.5
    container_name: newsapp-redis
    hostname: newsapp-redis
    restart: always
    expose:
      - 6379
    volumes:
      - dev-redis-data:/data
    env_file:
      - .env
    networks:
      backend-network:
        ipv4_address: 10.5.0.20

  celery_worker:
    build: ./
    container_name: newsapp-worker
    hostname: newsapp-worker
    restart: always
    command: poetry run python -m celery -A newsapp worker -c 4 -B --loglevel=debug
    env_file:
      - .env
    volumes:
      - ./src/:/app/src/
    networks:
      backend-network:
        ipv4_address: 10.5.0.30

volumes:
  dev-redis-data:
  dev-db:

networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1