version: '3.9'

services:
  web:
    build: ./
    container_name: newsapp-web
    hostname: newsapp-web
    restart: always
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/app/src/
    ports:
      - 80:8000
    env_file:
      - .env
    networks:
      backend-network:
        ipv4_address: 10.5.0.10
  
networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1