# Generated by Django 4.1.7 on 2023-03-20 19:01

import typing as t

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: t.List = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=63)),
                ("content", models.TextField(max_length=4095)),
            ],
        ),
    ]
