# Generated by Django 4.1.7 on 2023-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
